### ISSUE TITLE
Add Github Pages URL to the repository description

### ISSUE THREAD

**Issue by shinnn** [GoalSmashers/css-minification-benchmark#35]
![image](https://cloud.githubusercontent.com/assets/1131567/5735869/0754fe1c-9c11-11e4-9cb2-ddbac065a448.png)

I'd like to quickly jump to https://goalsmashers.github.io/css-minification-benchmark/.

**Comment by shinnn** [comment]
Any updates?

**Comment by jakubpawlowicz** [comment]
Done. Sorry I missed it before.

**Comment by shinnn** [comment]
Thanks :)

**Comment by tomByrer** [comment]
Yes, thanks; helpful for me also.

**Comment by shinnn** [comment]
Ah, no. This issue is not fixed yet.

I meant https://goalsmashers.github.io/css-minification-benchmark/, not https://github.com/GoalSmashers/css-minification-benchmark.

@jakubpawlowicz Can you update the description again?

**Comment by jakubpawlowicz** [comment]
Done.
